### ISSUE TITLE
[CY-4890] Add support for `eslint-config-xo-typescript`

### ISSUE THREAD

**Issue by twschiller** [codacy/codacy-eslint#1766]
https://github.com/xojs/eslint-config-xo-typescript

**Comment by machadoit** [comment]
Hi @twschiller we are facing a problem bumping the version of typescript by adding your configuration, based on the requirements `>=4.3` from https://github.com/xojs/eslint-config-xo-typescript/blob/main/package.json#L47

We currently have our typescript version as 4.2.4 that seems to run into some incompatibilities when it gets updated to 4.3.5. 

Is it possible for you to have your requirement as >=4.2 on your config? Also, feel free to contribute with a PR that solves the problems, like bellow when building the docker:

```node_modules/@types/jsforce/query.d.ts(70,13): error TS2368: Type parameter name cannot be 'never'.```

Otherwise we will want to tackle this eventually, just don't have an ETA for you.

**Comment by lolgab** [comment]
In [this commit](https://github.com/codacy/codacy-eslint/commit/e04c9c4e90ac4b7c653a3123926da4882dd9002f) I disabled the typescript typechecking on libraries which unlocked the Typescript update.
So, this issue is not blocked anymore.

**Comment by fregante** [comment]
Thank you!
