### ISSUE TITLE
Trailing semicolon is reported as error even though default settings of Prettier are to add it

### ISSUE THREAD

**Issue by qrsor** [codacy/codacy-eslint#373]
In our repository trailing semicolon of javascript files is being reported as issue even though be default prettier by default has the semicolons enabled at the end of the file. I've found that the setting is set to false in package.json of this plugins repository. Could it be the case that this setting is overriding Prettier's defaults?

**Comment by qrsor** [comment]
I've just noticed that this plugin is using prettier version < 2.x. Defaults are different there.

**Comment by lolgab** [comment]
Nice catch I have to say! I didn't think that ESLint could actually pick our own setting and apply it to user's code!
Did you manage to run prettier 2 through ESLint? Because it seems that the ESLint plugin is [stuck at version 1.x](https://github.com/prettier/eslint-plugin-prettier/pull/287). And since we are calling prettier through that we are tied to their support.

**Comment by qrsor** [comment]
I've managed to run Prettier 2 locally through ESLint. Installed using yarn. Both inspection and fix are working. Worked around the issue by adding `.prettierrc` into repository root.

**Comment by lolgab** [comment]
Thank you. I'm bumping prettier on our ESLint too.

**Comment by lolgab** [comment]
We have Prettier 2 now running in production.
Thank you @qrsor!
