### ISSUE TITLE
[CY-2376] [Feature Request] eslint-plugin-json-format

### ISSUE THREAD

**Issue by anthony0030** [codacy/codacy-eslint#608]
It would be great to have this plugin: "eslint-plugin-json-format" when I use Codacy with this plugin es lint fails.

**Comment by franciscodua** [comment]
Hi @anthony0030 
We had that plugin already. But we had to remove it due to several problems we had with it.
Examples:
https://github.com/codacy/codacy-meta/issues/349
https://github.com/codacy/codacy-meta/issues/415

And we have an open issue on the source repository that could solve these problems
https://github.com/Bkucera/eslint-plugin-json-format/issues/14.

Until that's fixed, we don't feel comfortable adding it again.

As a workaround, you can use the UI configuration in Codacy's dashboard, or remove the plugins from your configuration file.
Also, check JacksonLinter as a way to lint your JSON files. Or let us know why that linter doesn't work for you.

**Comment by anthony0030** [comment]
Hi @franciscodua :)

Thank you for your reply.

The error I get on the dashboard is: 
KubernetesDockerRunner: Container for codacy/codacy-eslint:4.0.8 exited with non-zero code 1
Error: Failed to load plugin 'json-format' declared in '.eslintrc': Cannot find module 'eslint-plugin-json-format'

Is it possible to just ignore plugins that don't exist and continue with the linting?

**Comment by franciscodua** [comment]
Hi @anthony0030 

We use a docker image without an internet connection to run Codacy tools, which means, for us to be able to run ESLint with a configuration that requires json-format, the plugin needs to be installed beforehand.

Unfortunately, I did not find a way to make ESLint ignore not installed plugins.

**Comment by lolgab** [comment]
I'm closing this issue as `wontfix` since we had this plugin and we had to remove if because of the problems it created to our tool. I suggest you to uninstall it because it causes a lot of false positives ( by assuming `JSON == Javascript` which is not true )
