### ISSUE TITLE
[CY-3266] TypeScript: some dependencies is imported as any

### ISSUE THREAD

**Issue by tscpp** [codacy/codacy-eslint#920]
**Summary**
When importing the [source-map](https://npmjs.com/source-map) package using TypeScript's module imports. It gets type "any" and ESLint fails for "unexpected any" in a lot of places.

----

I started using Codacy a few days ago, and it gave me this buttload of issues. So I checked the issues. ESLint/TS-ESLint caused them all. All of the issues were "unexpected any" issues, and all of them were caused by one dependency, [source-map](https://npmjs.com/source-map). I also installed the [@types/source-map](https://npmjs.com/@types/source-map) package as a dependency, but Codacy still failed. This doesn't happen with any other of my dependencies. Here is my GH project: [kolint/kolint](https://github.com/kolint/kolint). And here is the Codacy dashboard for my project: https://app.codacy.com/gh/kolint/kolint/dashboard.

----

```json
"devDependencies": {
	"@types/glob": "^7.1.3",
	"@types/mocha": "^8.0.4",
	"@types/node": "^14.14.9",
	"@types/source-map": "^0.5.7",
	"@typescript-eslint/eslint-plugin": "^4.8.1",
	"@typescript-eslint/parser": "^4.8.1",
	"eslint": "^7.14.0",
	"jison": "^0.4.18",
	"mocha": "^8.2.1",
	"ts-node": "^9.0.0"
},
"dependencies": {
	"glob": "^7.1.6",
	"knockout": "^3.5.1",
	"meriyah": "^3.1.6",
	"source-map": "^0.7.3",
	"typescript": "^4.1.2"
}
```

----

I have also tried to run ESLint locally with the versions `7.13.0` and `7.14.0`

**Comment by franciscodua** [comment]
Hi @tscpp 

That's a limitation of Codacy when running tools on the server-side. What is happening, is that Codacy does not install or builds your project (for security reasons). It only clones and runs the tool (ESLint in this case).
This means that dependencies that are not present [here](https://github.com/codacy/codacy-eslint/blob/master/package.json) are not available during the analysis.
For this reason, ESLint cannot find the types that you need.

As a workaround, you can either:
1. Disable that rule, which is not great, since it's a valuable rule
2. Run our CLI after building the project

Option number 2 might be a good fit for your project since you are already using GitHub actions and we made an action available for this purpose. You can find it [here](https://github.com/marketplace/actions/codacy-analysis-cli).
By using the CLI after building the project, you ensure the required node modules with the `types` information will be available for the analysis.

Let us know if this worked for you, and if you were able to correctly set up the CLI on your repository.

**Note:** Meanwhile, we'll evaluate `@types/source-map`, to check if we will make it part of Codacy's ESLint image by default, to better support repositories that use this dependency.

**Comment by tscpp** [comment]
Is there any way to get the report into Codacy or a comment in the current pull request to see the issues in a list instead of reading the text from the action's output?

**Comment by franciscodua** [comment]
Yes, there is @tscpp.

Follow these steps in order to have your results in Codacy and in your GitHub repository:
1. In Codacy, go to your repository settings (left-sidebar > Settings)
1. Search for "Repository analysis" and enable the option "Run analysis through build server" (this will let Codacy know that you are running the analysis in your CI)
1. Click on the Integrations tab (on the top of that same page) and under the "Status Checks" enable the annotations (this will start sending issues directly to GitHub)
1. On your GitHub Action, add an `upload: true` in your `with:` list (this will make the action upload the issues to Codacy so it appears on your dashboard)

**Note:** Choosing to upload your results imposes the limitation of not being able to use `pull_request` as a trigger for the action. Instead, you should choose `push`. This happens because the `pull_request` event does not have the commit SHA available and Codacy needs this information for the analysis (you can check GitHub's documentation about this event [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request).

**Double-Note:** You should avoid having plain text tokens in your project, instead follow [this guide](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) on how to use GitHub secrets instead.

---

**Alternative:**
Since you're using this as part of a public repository in GitHub you can use the new Code scanning feature (read more about it [here](https://github.blog/2020-09-30-code-scanning-is-now-available/)).

You can use it by:
1. Going to the security tab on your repository
1. Clicking the button "Set up code scanning" in front of "Code scanning alerts"
1. Choose "Codacy Security Scan" by Codacy

This will take you to a page to edit your new workflow YAML. You can adapt that workflow to your needs. That workflow however is not going to send issues to Codacy, it just sends them to your GitHub repository. So, if you want to have that information in your Codacy Dashboard, you still have to follow the steps described above

**Comment by TKasperczyk** [comment]
I followed the provided instructions, but Codacy still reports issues related to missing types in my repository. All of them are related to the [mongodb](https://www.npmjs.com/package/mongodb) package. My goal is to see the quality rating of my code directly in Codacy, which should take into account the types provided by the dependencies. 

Codacy settings:
- Settings -> Integrations -> Status checks -> Annotations - **enabled**
- Settings -> General -> Repository analysis -> Run analysis on your build server - **enabled**

GitHub settings:
- The Codacy webhook is configured and working without any issues ("Last delivery was successful" after each push)
- The project API key generated in Codacy is stored in "CODACY_PROJECT_TOKEN" (Actions secrets)
- The workflow is configured as described [here](https://github.com/marketplace/actions/codacy-analysis-cli) with the additional `upload: true` parameter in the `with:` section of "Run Codacy Analysis CLI". 

The YAML file can be found [here](https://github.com/TKasperczyk/MicroCMS/blob/main/.github/workflows/codacy-analysis.yaml). As you can see, there are two additional steps prior to running the CLI: `npm ci` and `npm run build`. The first step ensures that all dependencies are installed before running the analysis. 

There are no errors in the output of the workflow, and the last few lines suggest that the upload action was successful:

```
Run if [ true = true ]; then
Uploading results for gh/TKasperczyk/MicroCMS commit f926e134dd824779fdfb1dfca376eaf9810930f6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    55  100    55    0     0    100      0 --:--:-- --:--:-- --:--:--   100
100    55  100    55    0     0    100      0 --:--:-- --:--:-- --:--:--   100
{"success":"Final notification received successfully."}
```

I can see my commits in Codacy. They are getting analyzed after the corresponding workflow finishes all steps, but the issues related to missing types are still present: 

![Screenshot from 2022-06-21 13-46-48](https://user-images.githubusercontent.com/14127992/174791427-13e32eb1-123b-4bd3-a9d5-a3fc4fb6bc65.png)
